import './globals.css'
import Head from 'next/head'
import { Open_Sans } from 'next/font/google'
import logo from '@assets/logo.png'
import Link from 'next/link'

const openSans = Open_Sans({
  subsets: ['latin'],
})

export const metadata = {
  title: 'Litrary Council',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <Link rel="icon" className=" w-2" href={logo} />
      </Head>
      <body className={openSans.className} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  )
}
